parse:
	c -o parsing_example parsing_example.c ../mujinja.c
	./parsing_example
parse_file:
	cc -o parsing_file parsing_file_example.c ../mujinja.c
	./parsing_file
.PHONY=clen
clean:
	rm -f parsing_example
	rm -f parsing_file
